[package]
name = "waglayla-wrpc-example-subscriber"
description = "Waglayla wRPC subscription example"
publish = false
rust-version.workspace = true
version.workspace = true
edition.workspace = true
authors.workspace = true
include.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
futures.workspace = true
waglayla-consensus-core.workspace = true
waglayla-rpc-core.workspace = true
waglayla-wrpc-client.workspace = true
waglayla-notify.workspace = true
tokio.workspace = true
workflow-core.workspace = true
workflow-log.workspace = true
ctrlc.workspace = true
